language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  # PyPy versions
  - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0
# command to install dependencies
install:
  - pip install -r numpy_unit/requirements.txt
  - pip install .
# command to run tests
script: python numpy_unit/tests.py